name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore
    
    - name: Publish package to nuget
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}

